#include "nsISupports.idl"
[scriptable, uuid(f728830e-1dd1-4444-6666-fb9f414f2465)]
interface nsIScriptableWMPPlugin : nsISupports
{
	void play();
	void pause();
	void stop();
};

[scriptable, uuid(f728830f-1dd1-4444-6666-fb9f414f2465)]
interface nsIScriptableOgmpPlugin : nsISupports
{
	void func_one(in long value);
	void func_two(in string str);

    /* SIP UA interface */
	void load_user(in string uid, in long uidsz);
   void regist(in string fullname, in long fnsz, in string home_router,
					in string user_at_domain, in long seconds);
   void unregist(in string home_router, in string user_at_domain);
   void new_call(in string subject, in string info);
   void call(in string callee_at_domain);
   void answer(in long lineno);
   void bye(in long lineno);
    
	/*
	void Play();
	void Pause();
	void Stop();
	void quit();
	void DoPlay();
	void DoPause();
	void FastForward();
	void FastReverse();
	void ff();
	void rew();
	void rewind();
	void Seek(in double value);
	void Open(in string filename);
	double getTime();
	double getDuration();
	double getPercent();
	attribute string filename;
	attribute boolean ShowControls;
	attribute boolean fullscreen;
	attribute boolean showlogo;
	
	readonly attribute long playState;
	*/
	readonly attribute string version;

	readonly attribute nsIScriptableWMPPlugin controls;
};

/***
 * http://www.mozilla.org/projects/plugins/bi-directional-plugin-scripting.html
 */
[scriptable, uuid(f728830e-1dd1-4444-6666-fb9f414f2465)]
interface acmeJSObject : nsISupports
{
	string getProperty(in string name);
	void setProperty(in string name, in string value);
};

[scriptable, uuid(f728830e-1dd1-4444-6666-fb9f414f2465)]
interface acmeScriptablePlugin : nsISupports
{
	attribute acmeJSObject document;
};
